# Generated by Django 4.2.1 on 2023-06-19 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Perrito',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Id')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('raza', models.CharField(blank=True, max_length=50, verbose_name='Raza')),
                ('producto', models.CharField(blank=True, max_length=50, verbose_name='Producto')),
                ('blanco', models.CharField(blank=True, max_length=50, verbose_name='Blanco')),
                ('negro', models.CharField(blank=True, max_length=50, verbose_name='Negro')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perritos.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
