# Generated by Django 4.2.1 on 2023-07-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0002_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='blanco',
        ),
        migrations.RemoveField(
            model_name='perrito',
            name='negro',
        ),
        migrations.AddField(
            model_name='perrito',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
